# -*- coding: utf-8 -*-
"""FA19-BCS-140  A.1 IDS .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YrurqroxxL7IqWYOgw5iY0Jgo8hOgS-T
"""

import pandas as pd
import re
import seaborn as sn
import matplotlib.pyplot as plt

from google.colab import drive 
drive.mount('/content/drive')

#loaded the normalised dataset
df = pd.read_csv(('/content/drive/ My Drive/FA19-BCS-140 the-hello-dataset-fa22 (N).csv'))

y = df.iloc[[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17]]
print(y)

y=df['Name']
print(y)

check =df['Name']

check[21]

check = df['Name'].str[0]

check[18]

#Students name sarting with letter 'H' or 'h'
for n in range(len(check)):
  if(check[n] == 'H' or check[n] == 'h'):
    print(y[n])

#Students with 3 word names
for n in range(len(y)):
  x = y[n].split()
  if(len(x) == 3):
   print(y[n])

#CGPA of students above 3
check = df['CGPA']

check[18]

for n in range(len(check)):
  i = float(check[n])
  if(i >=3):
    print(check[n])

g = df['Gender']
print(g)

#Pie Chart for Gender
check = df['Gender']

male=0
female=0
for i in range(len(check)):
  if(check[i] == 'Male'):
    male=male+1
  if(check[i]=='Female'):
    female=female+1

male

import matplotlib.pyplot as plt
import numpy as np



y = np.array([male,female])

plt.pie(y)
plt.title('Pie Chart')
plt.show()

#Histogram
import matplotlib.pyplot as pyplot

gpa_list = []
cgpa = df['CGPA']
for x in range(len(cgpa)):
  if(check[x]== 'Male'):
    y= float(cgpa[x])
    gpa_list.append(y)

cgpa

fig, ax = pyplot.subplots(figsize=(8, 8))
(
    pd.cut(cgpa, bins=np.arange(1, 6, 0.5))
        .value_counts()
        .sort_index()
        .plot.bar(ax=ax)
)

#Scatter Plot for HSSC-1 marks
HSSC1 =df['HSSC-1']

male=[]
female=[]

for n in range(len(check)): 
  if(check[i] == 'Male'):
    x = int(HSSC1[n])
    male.append(x)
  if(check[i] == 'Female'):
     y = int(HSSC1[n])
     female.append(y)

import numpy
import matplotlib.pyplot as plt

arr = numpy.array(male)
arr1 = numpy.array(female)
plt.scatter(arr, arr)
plt.scatter(arr1, arr1)

plt.show()

#Bar Chart for Favourite Color
colour=df['FavoriteColor']

malecolor=[]
femlaecolor=[]

for n in range(len(check)): 
  if(check[n] == 'Male'):
    x = (colour[n])
    malecolor.append(x)
  if(check[n] == 'Female'):
     y = (colour[n])
     femlaecolor.append(y)

fig = plt.figure(figsize =(8, 8))
 
plt.bar(malecolor[0:10],femlaecolor[0:10])
plt.title('Bar Plot')
plt.show()

#Line Chart for Birth Months
birth= df['BirthMonth']

plt.plot(birth,y)
plt.title(' Birth Month Graph')
plt.xlabel('birthmonth')
plt.ylabel('y')
plt.show()